[package]
name = "data_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
logfile-parser = {path = "/home/fabian/TU_DRESDEN/PrivateMine/SOURCED/logfile-parser"}
serde = { version = "1.0.217", features = ["derive"] }
